### ISSUE TITLE
`DeFiCh/ain` - Implement getaccounthistory RPC on upstream

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#1025]
#### What would you like to be added:

Currently, we have `listaccounthistory` on `DeFiCh/ain`. However, there isn't a way to filter to get one AccountHistory and we need an RPC to get single account history to resolve balance transfer.

For reference, this is the key.
```cpp
struct AccountHistoryKey {
    CScript owner;
    uint32_t blockHeight;
    uint32_t txn; // for order in block
```

To be implemented on https://github.com/DeFiCh/ain first before we implement it here.

/assign @chanakasameera 
/triage accepted
/priority important-soon
/area packages

**Comment by surangap** [comment]
if `owner = xxxx, blockheight = N, txn-order = n` , it should only return the entry that matches the key `xxxxNn`. If not available, should return empty.
