### ISSUE TITLE
How to create/get a new wallet address

### ISSUE THREAD

**Issue by validblock** [DeFiCh/jellyfish#1033]
Hey,

how I can create a new address for a wallet?
Look at how far I've come:

```
import { WIF } from '@defichain/jellyfish-crypto'
import { MainNet } from '@defichain/jellyfish-network'
import { WalletClassic } from '@defichain/jellyfish-wallet-classic'
import { WhaleApiClient } from '@defichain/whale-api-client'
import { WhaleWalletAccount } from '@defichain/whale-api-wallet'

const client = new WhaleApiClient({url: 'https://ocean.defichain.com', version: 'v0'})
const wallet = new WalletClassic(WIF.asEllipticPair('XYZ'))
const account = new WhaleWalletAccount(client, wallet, MainNet)
```

However, I can't find any way to call the [getNewAddress](https://jellyfish.defichain.com/node/jellyfish/api/wallet#getnewaddress) method.

Thank you for support.

**Comment by fuxingloh** [comment]
WalletClassic is a non-hierarchical single-address wallet. You can't generate another address as the WIF (aka private key) you provide represent that single address.

Only [mnemonic support addresses derivation](https://github.com/DeFiCh/jellyfish/tree/main/packages/jellyfish-wallet-mnemonic).

And https://jellyfish.defichain.com/node/jellyfish/api/wallet#getnewaddress is a full node concept with `wallet.dat` managing the keys.

/area packages examples
