### ISSUE TITLE
strict json precision parsing

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/jellyfish#104]
#### What would you like to be added:
Its not critical but also a note.
Currently the precision is loose on
while:
```
parse (obj, type): any
parse({ foo: { bar: 123 }, bar: 123 }, { bar: 'bignumber' }
```

result:
```
{ foo: { bar: { BigNumber }}, bar: { BigNumber }}
```

expected:
```
{ foo: { bar: 123 }, bar: { BigNumber }}
```
note: 
Two issues will be facing while implement the strict precision
1. `ApiClient.call`'s resp object structure - `{ result, error, id }`
Ideally for rpc call is only passing the relevant precision mapping object
```
// better
getBlock(...args) {
  return await this.client.call(m, [], { number: 'bignumber' })
}

// Not so friendly
getBlock(...args) {
  return await this.client.call(m, [], { result: { number: 'bignumber' }})
}
```
2. Nested object will not be able to get parsed
Currently in order to remove the loose precision is to replace the `precision` by empty object `{}`
```
// remap.ts ln: 108-110
case MappingAction.DEEPLY_UNKNOWN:
  -- remapLosslessObj(losslessObj[k], precision)
  ++ remapLosslessObj(losslessObj[k], {})
  break
```
this causes the nested object cannot be parsed due to empty precision.

#### Why is this needed:
- technically `{foo: { bar: 123 }} !== { bar: 123 }`
- for note

But its also convince-able to remain the loose precision
1. Rare case in real scenario
```
parse({foo: {bar: 123}, bar: 123}}, {bar: 123})
```
assume `bar` is a crypto amount, so why not parsing both??

2. Its doable for but its required extra struct specification
```
parse({foo: {bar: 123}, bar: 123}}, { foo: {bar: 'number'}, bar: 'bignumber' })
// foo.bar remains number
// bar is converted to bignumber
```

**Comment by fuxingloh** [comment]
Thinking this simi simple way to do strict json precision parsing. Instead of "mapping", we could do "path" based.

```ts
const object = {
  value: 0,
  values: [
    9,
    9,
  ],
  items: [
    {
      a: 10,
      b: 11,
    },
    {
      a: 20,
      b: 21,
    }
  ],
  deep: {
    c: 0,
    d: 0,
  }
}

// you either define bignumber or it default to number
const pathPrecision = {
  value: 'bignumber', // 0 = bignumber
  values: 'bignumber', // [9,9] = bignumber
  items: {
    a: 'bignumber',  // items: [{a: 10}, {a: 20}] = bignumber
                     // items: [{b: 11}, {b: 21}] = number
  },
  deep: 'bignumber' // {c:0,d:0} get parsed to bignumber
}
```

**Comment by fuxingloh** [comment]
> https://github.com/DeFiCh/jellyfish/pull/119/checks?check_run_id=2341762608

@fuxingloh a edge case to take note of when implementing strict precision parsing.
