### ISSUE TITLE
`/apps/legacy-api` - HealthCheck via Actuator

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#1060]
#### What would you like to be added:

`_actuator/probes/...` health check. We can follow the ocean-api design towards how we can implement the health-check. Should also import `apps/ocean-api` files to keep it DRY.

#### Why is this needed:

To take down legacy-api nodes when they end up in a bad state.

/triage accepted
/assign @eli-lim
/area apps
/priority important-soon

**Comment by fuxingloh** [comment]
Following this design: https://github.com/DeFiCh/jellyfish/blob/main/apps/ocean-api/src/controllers/ActuatorController.ts

**Comment by eli-lim** [comment]
Update: simply importing the files from apps/ocean-api will cause nest to fail some dependency look-ups. Trying to find a way to share the `ActuatorModule` between the two (possibly more next time) apps

**Comment by ivan-zynesis** [comment]
We will need something like `jellyfish-api-template`. All of our API going to need this implemented, I am copy pasting all those modules in the new rich-list-api at the moment and leaving them as it is and wait for the solution here.

**Comment by fuxingloh** [comment]
> We will need something like `jellyfish-api-template`. All of our API going to need this implemented, I am copy pasting all those modules in the new rich-list-api at the moment and leaving them as it is and wait for the solution here.

@eli-lim worked on https://github.com/DeFiCh/jellyfish/pull/1078
