### ISSUE TITLE
`testpoolswap` - add `auto` and `true` arguments to display optimal path and prices for composite swap

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/jellyfish#1065]
#### What would you like to be added:
We would like to add `auto` and `true` arguments for `testpoolswap` so we can use get the optimal path and prices for a swap.

#### Why is this needed:
Currently, the path finding algorithm is done on the client side (both path and prices) and it's causing some noticeable performance issues. Note, address can be from anyone (not validated if you are the owner).

```
testpoolswap '{"from":"address","tokenFrom":"DFI","amountFrom":1,"to":"address","tokenTo":"GOOGL"}' auto true
```

```
Sample response:
{
  “path”: “auto”,
  “pools”: [
    “5",
    “17”
  ],
  “amount”: “35102.57338662@15”
}
```

**Comment by fuxingloh** [comment]
/triage accepted
/area packages
/priority important-soon
/assign @eli-lim 

Similar to #48 but expanding on top of the existing `testpoolswap` interface as requested by @thedoublejay.

**Comment by eli-lim** [comment]
Linked - https://github.com/DeFiCh/ain/issues/1114

Do we want to present the "optimal path" - whether it's a direct or composite swap?
If so, https://github.com/DeFiCh/ain/pull/1115 will need to be adjusted very slightly

**Comment by eli-lim** [comment]
To reduce computation load on defichain, shall we do expose this _optimal path_ finding as an endpoint on Whale instead?

**Comment by thedoublejay** [comment]
@eli-lim Yup! Let's go with optimal path.

**Comment by thedoublejay** [comment]
@eli-lim Ok understand your point now. We can move this calculation on Whale side.
