### ISSUE TITLE
`apps/website` - move website out of apps

### ISSUE THREAD

**Issue by kodemon** [DeFiCh/jellyfish#1071]
#### What would you like to be added:

Move `apps/website` out of `apps/` and into root, or a new folder which befits its scope more clearly.

#### Why is this needed:

In our ongoing consolidation efforts `apps` consists of containers that is to be part of a jellyfish services, and `website` falls into a different category in the upcoming scope of `apps`.

Since website is responsible for documentation and is built outside of this scope via `netlify` it will serve us well to have clear cut concerns between `apps` and `website`. This simplifies our other processes by scoping our structure more correctly making building docker containers for `apps` vs `website` via netlify straight forward without needing to add complex rules to our build processes going forward.

```
apps # Jellyfish services/apps/apis
  legacy-api
  ocean-api
  playground-api
  whale-api
website # Jellyfish Landing/Documentation
```

**Comment by fuxingloh** [comment]
/area core workflow
/triage accepted
/assign @kodemon 

There is also another issue with our current approach that is pretty annoying. More info here: https://docs.netlify.com/configure-builds/common-configurations/monorepos/#declare-dependencies-at-the-root-level-and-within-a-subdirectory

Perhaps something to look into too.

**Comment by kodemon** [comment]
Added follow up ticket to get website move done faster, added follow up #1087 for netlify adjustments
