### ISSUE TITLE
`packages/jellyfish-api-core`: map `hex` field in `AccountOwner` interface.

### ISSUE THREAD

**Issue by surangap** [DeFiCh/jellyfish#1075]
#### Anything else we need to know?:
in `packages/jellyfish-api-core/src/category/account.ts`

```
export interface AccountOwner {
  asm: string
  reqSigs: BigNumber
  type: string
  addresses: string[]
}
```
should be 
```
export interface AccountOwner {
  asm: string,
  hex?: string,
  reqSigs: BigNumber
  type: string
  addresses: string[]
}
```

**Comment by cwkang1998** [comment]
Looking at https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/core_write.cpp#L168 and https://github.com/DeFiCh/ain/search?q=ScriptPubKeyToUniv, and after a discussion with surangap,  it seems that when calling the `listaccounts` rpc when `verbose === true`, the `hex` field **will** be provided. As such, the `hex` field should be non-optional.

Expected interface should be:
```typescript
export interface AccountOwner {
  asm: string,
  hex: string,
  reqSigs: BigNumber
  type: string
  addresses: string[]
}

```
