### ISSUE TITLE
documenting list & get PoolPair endpoint on https://jellyfish.defichain.com/ocean/

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#1098]
#### What would you like to be added:

DeFiChain community developers are requesting documentation for PoolPair. For now, we only need these two endpoints documented:
- https://github.com/DeFiCh/whale/blob/9d0ab6c0b78fa4d1d403a85bdd96ff2cfbf0c3e9/packages/whale-api-client/src/api/poolpairs.ts#L18
- https://github.com/DeFiCh/whale/blob/9d0ab6c0b78fa4d1d403a85bdd96ff2cfbf0c3e9/packages/whale-api-client/src/api/poolpairs.ts#L28

/triage accepted
/assign @canonbrother 
/area docs
/priority important-soon

**Comment by canonbrother** [comment]
hmm... wondering do we need a API documentation generation tool like swagger?? :thinking:

**Comment by fuxingloh** [comment]
Yeah, `nestjs` has it but probably not for this iteration of the project, something for the future.
