### ISSUE TITLE
missing reward value for all DUSD Pools on Ocean API

### ISSUE THREAD

**Issue by 3Goldjungen** [DeFiCh/jellyfish#1179]
#### What happened: 
When using https://ocean.defichain.com/v0/mainnet/poolpairs
for all DUSD pairs rewardPct is 0.  

#### What you expected to happen:
Either the rewardPct should contain the correct value or a new field rewardLoanPct is needed.
Alternative would be new api call like in the desktop wallet: https://ocean.defichain.com/v0/mainnet/listgovs

labels:
`apps/ocean-api` `area/apps`

**Comment by 3Goldjungen** [comment]
added labels
/apps/ocean-api
/area/apps

**Comment by 3Goldjungen** [comment]
`area/apps`

**Comment by 3Goldjungen** [comment]
'area/apps' 'apps/ocean-api'

**Comment by fuxingloh** [comment]
This is kinda tricky, rewardPct was provided by upstream `defid`. However, I think it's a good idea to introduce it to ocean API.

/area apps
/triage accepted

**Comment by ivan-zynesis** [comment]
> This is kinda tricky, rewardPct was provided by upstream `defid`. However, I think it's a good idea to introduce it to ocean API for loan
> 
> /area apps /triage accepted

I am reluctant to add extra logic to `jellyfish-api-core` (which is simple rpc call), perhaps only add it in https://github.com/DeFiCh/whale/issues/739? Any opinion?

**Comment by ivan-zynesis** [comment]
Will be handled in https://github.com/DeFiCh/whale/issues/739
