### ISSUE TITLE
Chore: `whale-api-wallet` migration

### ISSUE THREAD

**Issue by ivan-zynesis** [DeFiCh/jellyfish#1257]
#### What would you like to be added:
Migrate https://github.com/DeFiCh/whale/tree/8195727e359953c2dba1ab208cfdf3beb9706eab/packages/whale-api-wallet
Take this opportunity to include unit test.

#### Why is this needed:
Main sdk wallet client implementation will use to deal with defichain via ocean infrastructure

**Comment by cwkang1998** [comment]
This is actually already done via  #1167.
I would be including the unit tests following it.
