### ISSUE TITLE
`packages/jellyfish-api-core`: Add DFI2203 Futures work

### ISSUE THREAD

**Issue by surangap** [DeFiCh/jellyfish#1268]
#### What would you like to be added:
map endpoints related to https://github.com/DeFiCh/ain/pull/1155

#### Why is this needed:
https://github.com/DeFiCh/dfips/issues/127

**Comment by jingyi2811** [comment]
futureswap: @surangap 
withdrawfutureswap: 
listpendingfutureswaps: @jingyi2811
getpendingfutureswaps: 
getfutureswapblock:

**Comment by jingyi2811** [comment]
After reading the python code, I believe futureswap and withdrawfutureswap RPCs are harder and you may spend more time on them. Therefore, I pick the rest of the RPCs
