### ISSUE TITLE
Token Ids are changing on /v0/regtest/tokens?size=200 with mocked playground

### ISSUE THREAD

**Issue by pierregee** [DeFiCh/jellyfish#1297]
#### What happened:

The token ids returned from `/v0/regtest/tokens?size=200` keeps changing when re-running `docker-compose` on light wallet
On the screenshots below:
**e.g DUSD = id: 13 and DUSD= id: 15** also happens in other tokens

```
# docker-compose.yml
whale:0.32.1
playground-api:2.32.1
```
```
jellyfish: 2.32.1
```

#### What you expected to happen:
The token id should be consistent on mocked playground regardless if `docker-compose` is re-run multiple times

#### How to reproduce it (as minimally and precisely as possible):
- Rerunning the docker twice then the said API endpoint tokenIds will change

#### Anything else we need to know?:

![image](https://user-images.githubusercontent.com/13292662/160755277-ccae96fd-9cff-4336-a7d2-bbafa2abb875.png)
![image](https://user-images.githubusercontent.com/13292662/160755286-53b8a083-fc3c-4a8a-b880-d5a833655bc2.png)

**Comment by canonbrother** [comment]
suspected 
https://github.com/DeFiCh/jellyfish/blob/9620bb6f52cab249735a0d6e02cb2f5309363b70/apps/playground-api/src/AppConfiguration.ts#L9
