### ISSUE TITLE
`bot` to automate setting of GovVar to access new hard fork features

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/jellyfish#1298]
#### What would you like to be added:
Need more info @fuxingloh

**Comment by fuxingloh** [comment]
https://github.com/DeFiCh/jellyfish/blob/dd15230a02dd63dc6c88348fe1c06a8d7e4e224d/packages/jellyfish-api-core/__tests__/category/loan/paybackLoan.test.ts#L1597-L1602

/triage accepted
/area apps
/priority important-soon

To access features in the playground for testing.
