### ISSUE TITLE
subpath exports for large packages

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#130]
#### What would you like to be added:
>  Available in NPM >v12.7.0

Custom subpaths can be defined along with the main entry point by treating the main entry point as the "." subpath:

```json
{
  "main": "./dist/index.js",
  "exports": {
    ".": "./dist/index.js",
    "./submodule": "./dist/bech32.js"
  }
}
```

This allow loading a sub path
```ts
import submodule from '@defichain/jellyfish-crypto/bech32';
// Loads ./node_modules/@defichain/jellyfish-crypto/dist/bech32.js
```

#### Why is this needed:

As the modules and packages grows, it is becoming increasingly complex to manage imports and exports. Bundling all exports into one `index.js` file for small modules make senses but for large more complex modules it is harder to effectively manage conflicts. E.g. `jellyfish-api-core`, hence it is wise to implement subpath exports vs named exports for larger packages.

**Comment by fuxingloh** [comment]
Subpath exports is not yet supported in typescript, and it seems like it will be part of TypeScript 4.3, May 25 final release.
Let's wait for that.

https://github.com/microsoft/TypeScript/issues/42762

**Comment by Vasile-Peste** [comment]
There is no way to test the feature in beta? There is no hint on how this is going to be implemented? What about subpath type files?

We should be able to as follows.

`
{
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": "./dist/index.js",
    "./submodule": "./dist/bech32.js"
  },
  "exportsTypes": {
    "./submodule": "./dist/bech32.d.ts"
  }
}
`

**Comment by fuxingloh** [comment]
Hi @Vasile-Peste, currently all of the packages are still exported in `packages/*/dist/index.js` and you can import them as such: `import { EllipticPair, dSHA256 } from '@defichain/jellyfish-crypto'` and use them as it is (you need to use the @next branch tho). Just that before beta there might be expected breaking changes to how exports/imports are done. 

This ticket was created to better tackle exports/imports as this mono repo grows in size. AFAIK `exportsTypes` is not a supported feature in typescript (please correct me if I am wrong).

**Comment by Vasile-Peste** [comment]
> Hi @Vasile-Peste, currently all of the packages are still exported in `packages/*/dist/index.js` and you can import them as such: `import { EllipticPair, dSHA256 } from '@defichain/jellyfish-crypto'` and use them as it is (you need to use the @next branch tho). Just that before beta there might be expected breaking changes to how exports/imports are done.
> 
> This ticket was created to better tackle exports/imports as this mono repo grows in size. AFAIK `exportsTypes` is not a supported feature in typescript (please correct me if I am wrong).

Sorry to disappoint, I wrote the message on the wrong repository... 🤦🏻
