### ISSUE TITLE
jellyfish-wallet-mnemonic to support encrypt and decrypt

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#133]
#### What would you like to be added:

1. `jellyfish-wallet-mnemonic` with `encrypt` and `decrypt` function extended above 24 word.
2. 24 word must unlock the wallet, this just encrypt the 24 words on rest.

#### Why is this needed:

The 24 words mnemonic seed should serve as a cold storage of your HD seed.
However the 24 words should not sit in your device (phone/browser/desktop) unencrypted as rest.
Encryption can be done with biometric authentication provided by device, `jellyfish-wallet-mnemonic` just need to provide the interface to do it.

Reference example: https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki

**Comment by ivan-zynesis** [comment]
@fuxingloh Not very certain about the requirement, this is allow user store an the encrypted mnemonic during `first time create` or `import`? The encrypted is protected with a "simpler" (than the ori mnemonic seed) user selected passphrase?

```
interface EncryptionOptions {
  passphrase: string
  encryptedSetter: () => void
  encryptedGetter: () => string
}

static fromSeed (seed: Buffer, options: Bip32Options, encOpt?: EncryptionOptions) {}
```

**Comment by fuxingloh** [comment]
1. Generate mnemonic seed for cold storage
2. Generated mnemonic seed must be the actual seed used for signing transaction
3. Mnemonic seed stored at rest is dangerous
4. Encrypt mnemonic seed while it's at rest
5. When the user wants to perform a transaction, decrypt encrypted mnemonic seed

So yeah, the encryption protects the original mnemonic seed [at rest](https://en.wikipedia.org/wiki/Data_at_rest). It is only loaded into memory when it's required for a brief period.

**Comment by fuxingloh** [comment]
There is also some flow/complications to this, as the wallet should only encrypt private key. The pubKey should be accessible at rest.
