### ISSUE TITLE
jellyfish-transaction tests should be run against testcontainers for compatibility

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#150]
#### What would you like to be added:

Additional testing against testcontainers for `jellyfish-transaction` for better compatibility. This can be done on a `RegTestContainer` without masternode configured for a quick round of tests. `__testcontainers__` directory can be used to separate the tests that require testcontainers to be up.

#### Why is this needed:

This provide additional guarantee the txn generated by jellyfish-transaction will all always in compliance with DeFi Blockchain.

**Comment by fuxingloh** [comment]
I will wait for #162 before I add in the required tests for DfTx. As some of the test pre-conditions are very tedious to setup without known types.

**Comment by fuxingloh** [comment]
Wait for https://github.com/DeFiCh/jellyfish/pull/185 to be merged in for better testing QOL

**Comment by ivan-zynesis** [comment]
@fuxingloh I am not very sure for the scope should be covered here? What kind of "transactions"? I am imagining things like

eg:
spend utxo (normal send)
spend token
and every custom DfTx that require private key signed

**Comment by ivan-zynesis** [comment]
> @fuxingloh I am not very sure for the scope should be covered here? What kind of "transactions"? I am imagining things like
> 
> eg:
> spend utxo (normal send)
> spend token
> AND/OR every custom DfTx that require private key signed

```
describe: DfTx/utxos-to-account
  before: start container -> generate address -> mint balance
  it: composeBuffer(UtxosToAccount) -> submit data to container?
```

do these for every DfTx?

**Comment by fuxingloh** [comment]
You can take a look at https://github.com/DeFiCh/jellyfish/pull/237

It will provide you an understanding of how to test the DfTx transaction.

**Comment by fuxingloh** [comment]
/close in favour of #244 
Any issues that are required for #150, must create a ticket to tackle it.
