### ISSUE TITLE
error installing via npm 'No matching version found for @defichain/jellyfish-core@^0.0.3.'

### ISSUE THREAD

**Issue by gamsterx** [DeFiCh/jellyfish#232]
#### What happened:
`npm i @defichain/jellyfish --save --include=dev`

```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @defichain/jellyfish-core@^0.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```
#### What you expected to happen:
Successful installation

#### How to reproduce it (as minimally and precisely as possible):
`npm i @defichain/jellyfish --save --include=dev`

**Comment by fuxingloh** [comment]
> #### What happened:
> `npm i @defichain/jellyfish --save --include=dev`
> 
> ```shell
> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for @defichain/jellyfish-core@^0.0.3.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> ```
> 
> #### What you expected to happen:
> Successful installation
> 
> #### How to reproduce it (as minimally and precisely as possible):
> `npm i @defichain/jellyfish --save --include=dev`

Hey @gamsterx thanks for opening an issue, we are currently in heavy development mode hence we publish everything into `@next` release. That would require you to install via `npm i @defichain/jellyfish@next` for now everything. I apologise for the confusion. We are rushing to push out a proper release on the `@latest` ASAP.

**Comment by gamsterx** [comment]
Hi @fuxingloh, 
thanks! I was able to install via `@next`. 

What´s the best way to learn how to use this package? I´m not yet familiar with blockchain/defichain APIs. 

Currently I´m not even able to connect the client via localhost (`request to http://localhost:8554/ failed, reason: connect ECONNREFUSED 127.0.0.1:8554`) or OceanProvider (`fetchError: request to https://ocean.defichain.com/ failed, reason: getaddrinfo ENOTFOUND ocean.defichain.com`). Maybe I´m missing some prerequisites?

My first goal is to connect to my local defichain app (is that even possible?) or some arbitrary node to get some account balances and transactions.

Do you have a public developer chat (discord, slack or something else) where I and other devs could ask technical questions?

**Comment by fuxingloh** [comment]
We currently have docs in https://jellyfish-defi.netlify.app/docs for usage details, the API that is available now is created for light wallet development. It may or may not be sufficient enough for your use case.

Another way to look at it is looking at our tests, it provides a good understanding of the expected use case: https://github.com/DeFiCh/jellyfish/blob/87d3e7b762abaf593325fa12fe1f4de7e722d2c3/packages/jellyfish-api-core/__tests__/category/wallet.test.ts#L520-L526

While for connection to your local defichain app node, you need the full URL to do that. It's somewhere in your defi config directory. A URL should look something like this: `http://${user}:${password}@127.0.0.1:${port}/`. Make sure you don't expose this information beyond your secured environment.

Your first goal is totally possible.

OceanProvider is still a work in progress, as it is part of the light wallet timeline. https://github.com/DeFiCh/ocean

We do not have a public developer chat yet, we plan to have that up when this goes into beta. It's still in alpha now. We are also planning to add a jellyfish playground when this hits alpha. A playground will allow you to play around with jellyfish protocols for DeFi Blockchain. https://github.com/DeFiCh/jellyfish/issues/65

**Comment by gamsterx** [comment]
Thank you @fuxingloh for the info! I will take a look at the docs and start playing around.
