### ISSUE TITLE
refactor `jellyfish-address` implementation to be lighter

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#239]
> https://github.com/DeFiCh/jellyfish/pull/189#pullrequestreview-661119711

#### What would you like to be added:

Refactoring of `jellyfish-address` code/logic to be lighter, currently, it's too complex. Dangerous technical debt.

#### Why is this needed:
```diff
@@           Coverage Diff            @@
##             main     #189    +/-   ##
========================================
  Coverage   96.21%   96.22%            
========================================
  Files          66       74     +8     
  Lines        1718     1958   +240     
  Branches      235      264    +29     
========================================
+ Hits         1653     1884   +231     
- Misses         65       74     +9     
```

I would expect around `<15` code logical branches for `jellyfish-address` but there were `+29` which is 10% more than the current combined mono repo code base.

https://github.com/DeFiCh/jellyfish/pull/237 has only `+7` for comparison and it has a much more complex implementation design. Clearly, there is much to optimize, the more code there is, the more there is to maintain. Less is more.

**Comment by ivan-zynesis** [comment]
@fuxingloh I am taking this if there is no other more urgent issue.

**Comment by fuxingloh** [comment]
> @fuxingloh I am taking this if there is no other more urgent issue.

Might want to get #244 through soon, else you can take this.

You might want to do it slowly over a few PRs instead of all at once. The idea is to use deterministic logic to detect with as little logical branches as possible. The logical branch is quite obvious, there should be like 7 or so logical branches.
