### ISSUE TITLE
Light wallet or third party dev friendly txn builder to generate signed transaction

### ISSUE THREAD

**Issue by ivan-zynesis** [DeFiCh/jellyfish#244]
Continue from #237 , extend the implementation for every required DfTx (prioritize light wallet requirement only)

Built [transaction](https://github.com/DeFiCh/jellyfish/blob/main/packages/jellyfish-transaction/src/tx.ts#L59) should be signed and ready for broadcast.

## CustomTx
- [x] utxosToAccount: `'U'` #245 
- [x] accountToUtxos: `'b'` #267 
- [x] accountToAccount: `'B'` #267 
- [x] addPoolLiquidity: `'l'` #268
- [x] removePoolLiquidity: `'r'` #268

## CustomTx (Oracles)
- [ ] appointOracle : `'o'` @monstrobishi 
- [ ] removeOracle: `'h'` @monstrobishi 
- [ ] updateOracle: `'t'` @monstrobishi 
- [ ] setOracleData: `'y'` @monstrobishi

**Comment by fuxingloh** [comment]
The priority is in the exact order above, best to create separate PR for each of them.
