### ISSUE TITLE
Filter `txtype` Parameter of `listAccountHistory()` doesn´t seem to filter AccountHistory

### ISSUE THREAD

**Issue by gamsterx** [DeFiCh/jellyfish#252]
#### What happened:
I want to get a filtered list of transactions via `listAccountHistory`. I used the `txtype` options parameter which didn´t seem to have any effect. 

I tried different strings like `PoolSwap` or `Commission` with the same unfiltered result.

As this project is currently in heavy development the docs are limited at this point in time. I managed to find the following info:
`@param {string} [options.txtype] Filter by transaction type, supported letter from 'CRTMNnpuslrUbBG`

I have no clue what the letters suppose to mean. Can somebody explain?

An example from the tests shows a `txtype: 'M'` which in my case also didn´t filter the transactions.

#### What you expected to happen:

I expect to get only history objects of the `txtype` `Rewards` or `Commission` or `PoolSwap` or `...`.

#### How to reproduce it (as minimally and precisely as possible):

` "@defichain/jellyfish": "^0.3.0"`

```ts
import { Client } from "@defichain/jellyfish";
import { AccountHistoryOptions } from "@defichain/jellyfish-api-core/dist/category/account";

const client = new Client(
    "http://USER:PW@localhost:8555"
  );
  
  const options: AccountHistoryOptions = {
    txtype: "",
  };

  const accountHistories = await client.account.listAccountHistory(
    "mine",
    options
  );
```

**Comment by fuxingloh** [comment]
Those characters are the custom DeFi transactions. See https://github.com/DeFiCh/jellyfish/issues/108 for more info.

Thanks for creating this issue, appreciate it! I will assign this to be worked on, our priority is still light wallet. But this is something valid that we need to address.

/assign @jingyi2811 we need to add `export enum TxType {}` and update the documentations on `JSDoc` and `website/`
/area jellyfish-api-core
/triage accepted

**Comment by siradji** [comment]
@fuxingloh , this issue was address and fixed in  `Add account.historyCount RPC` #265.

**Comment by fuxingloh** [comment]
> @fuxingloh , this issue was addressed and fixed in `Add account.historyCount RPC` #265.

That RPC is for `historyCount`, this is for `listAccountHistory`. 
https://github.com/DeFiCh/jellyfish/blob/9d311db3c3f905fc05fdecdacc0ab96176c291f0/packages/jellyfish-api-core/src/category/account.ts#L110-L117
