### ISSUE TITLE
test account history in `jellyfish-api-core` extensively

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#292]
#### What would you like to be added:

Account history RPCs should be tested extensively.

#### Why is this needed:

Currently, the test within Account History is very limited. It only checks the soundness of the RPC does not test it end to end with different setups. We need complete/full e2e testing on account history to prevent regression.

**Comment by fuxingloh** [comment]
@aikchun you need to work on this soon before moving to working on explorer related work

**Comment by aikchun** [comment]
@fuxingloh What are some of the various setups and scenarios that should be tested?

And this is for `listAccountHistory` and `accountHistoryCount` rpcs?

**Comment by fuxingloh** [comment]
1. Pool Rewards
2. Pool Swap
3. AccountToAccount
4. UTXO To Account
5. Account to UTXO
6. Pool Enter
7. Pool Exit

**Comment by aikchun** [comment]
>     1. Pool Rewards
> 
>     2. Pool Swap
> 
>     3. AccountToAccount
> 
>     4. UTXO To Account
> 
>     5. Account to UTXO
> 
>     6. Pool Enter
> 
>     7. Pool Exit

If I infer the code correctly, for Pool Enter, this happens when user calls `addpoolliquidity` rpc right?
Pool Exit -> `removepoolliquidity` rpc
Pool Swap -> `poolswap` rpc

I'm not too sure when Pool Rewards happen.

**Comment by fuxingloh** [comment]
> > ```
> > 1. Pool Rewards
> > 
> > 2. Pool Swap
> > 
> > 3. AccountToAccount
> > 
> > 4. UTXO To Account
> > 
> > 5. Account to UTXO
> > 
> > 6. Pool Enter
> > 
> > 7. Pool Exit
> > ```
> 
> If I infer the code correctly, for Pool Enter, this happens when user calls `addpoolliquidity` rpc right?
> Pool Exit -> `removepoolliquidity` rpc
> Pool Swap -> `poolswap` rpc
> 
> I'm not too sure when Pool Rewards happen.

Pool Reward happens at every block gen, you need to allocate pool reward to a pool via set governance.
