### ISSUE TITLE
refactor all test in `jellyfish-api-core` to be independent 

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#295]
#### What would you like to be added:
All test in `jellyfish-api-core` to be refactored such that they are independent with each file for each method.

```
jellyfish-api-core/__tests__/category/
├── account/
│  ├── listAccounts.test.ts
│  └── getAccount.test.ts
├── blockchain/
│  └── getBlockchainInfo.test.ts
```

Within the test itself, spin up as many containers as required for independent testing. Be selective of what container you need, if you don't need an individual container for various setup, just use one container. Some test only required one container while others need different scenario with a clean chain.

<details>
<summary>Single Chain</summary>

```ts
const container = new MasterNodeRegTestContainer()
const client = new ContainerAdapterClient(container)

beforeAll(async () => {
  await container.start()
  await container.waitForReady()
  await container.waitForWalletCoinbaseMaturity()
})

afterAll(async () => {
  await container.stop()
})

it('should setWalletFlag', async () => {
  ...
})
```

</details>

<details>
<summary>Multiple Chains</summary>

```ts
describe('regtest without masternode', () => {
  const container = new RegTestContainer()
  const client = new ContainerAdapterClient(container)

  beforeAll(async () => {
    await container.start()
    await container.waitForReady()
  })

  afterAll(async () => {
    await container.stop()
  })

  it('should setWalletFlag', async () => {
    ...
  })
})

describe('with masternode', () => {
  const container = new MasterNodeRegTestContainer()
  const client = new ContainerAdapterClient(container)

  beforeAll(async () => {
    await container.start()
    await container.waitForReady()
    await container.waitForWalletCoinbaseMaturity()
  })

  afterAll(async () => {
    await container.stop()
  })

  it('should setWalletFlag', async () => {
    ...
  })
})
```

</details>

#### Why is this needed:

It’s getting very difficult to maintain side-effect and writing independent tests. Writing a clean and independent test is not easy, it requires a certain mastery with strong testing principles. Refactoring `__tests__` in `jellyfish-api-core` will allow us to have a cleaner testing culture.

**Comment by jingyi2811** [comment]
Working on account rpcs
