### ISSUE TITLE
DeFi 'super-node' upstream proxying service

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#30]
#### What would you like to be added:

An API gateway/proxy service for DeFiChain jellyfish users.

#### Why is this needed:

Currently, the `JSON-RPC` channel in `DeFiCh/ain` is password protected by default. Important and intentional by design. However, this makes it difficult to setup password-less service for public to uplink to. It does not make sense to implement API gateway/proxy features in C++. This will also offload the networking layer to a purpose built provider. (👀 NGINX & Related)

#### We need:
1. Whitelist based service/system for super-node hosting to on/off certain RPCs?
2. A build of `DeFiCh/ain` without wallet features
3. HTTPS & HTTP2 capable gateway for TLS termination
4. Cloud Native - docker capable setup

#### We should:
1. Use infrastructure as code for deployment
2. Open source the setup for anyone that wants to run it
3. Use solution with high memory/networking pressure capability over fully featured solutions.

**Comment by fuxingloh** [comment]
@uzyn @monstrobishi what are your thoughts on this?

**Comment by uzyn** [comment]
It will be publicly hosted nodes with no password protection, similar Infura.

e.g. https://ocean.defichain.com is the endpoint and it will be mapped to various stateless nodes. 

We can add HTTPS/HTTP2 with nginx load balancer in front and build an image with proxy and node readily available.

**Comment by monstrobishi** [comment]
Thanks @uzyn I was going to reply the same

**Comment by monstrobishi** [comment]
But we can still look into this suggestion past the initial stage

**Comment by fuxingloh** [comment]
Thanks for the inputs!

1. I will create a repo in due time called `DeFiCh/ocean` to codename the development. 
2. Draft a RFC for the technical design of the project, will tag y'all when it's ready for review.

**Comment by fuxingloh** [comment]
Closed in favour of DeFi Whale & DeFi Ocean projects that are work in progress.
