### ISSUE TITLE
return `txid` in `Transaction`

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/jellyfish#303]
#### What would you like to be added:

Add a `txid` parameter to `Transaction` and populate when building the transaction

#### Why is this needed:

Some DeFiChain features such as Oracles and ICX rely on the txid to refer to objects such as Price Oracles and Orders, it can be handy to retrieve the `txid` to store for later purposes.

**Comment by monstrobishi** [comment]
Can do something like this:
```
  let buffer = new SmartBuffer();
  new CTransaction(transaction).toBuffer(buffer);
  return dSHA256(buffer.toBuffer()).reverse().toString('hex');
```

**Comment by ivan-zynesis** [comment]
There is another ticket (#132) will split all crypto operations and dependencies from `jellyfish-transaction` to make it clean and platform independent as some crypto lib vary for different platform. Kind of conflict of interest, perhaps this can be done in some util manner, will see how it gone after ticket132.
