### ISSUE TITLE
`PoolPairInfo.customRewards` is nullable?

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#393]
#### What happened:

`PoolPairInfo.customRewards` appears to be optional when testing in DeFiCh/whale, but they are not optional in jellyfish?

/area jellyfish-api-core
/triage accepted
/priority urgent-now
/assign @canonbrother to investigate this, thanks

**Comment by canonbrother** [comment]
Yes poolpair.customeRewards should be nullable
https://github.com/DeFiCh/ain/blob/7a430185fd3029e9ee8974fde4e65c715fb9db04/src/masternodes/rpc_poolpair.cpp#L51-L59
