### ISSUE TITLE
Automatic Conversion of Integer/Fraction for MaxPrice in `dftx_pool.ts`

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#439]
#### What would you like to be added:

Automatically convert Integer & Fraction to their correct implementation. This allows easier use of MaxPrice without having to convert it yourself. #429 is partially flawed PR.

1. `maxPrice = integer * PRECISION + fraction`
2. PRECISION is fixed to `100000000`
3. therefore maxPrice of A/B trade 100/50 = `2.0` would be an integer of `2` and fraction of 0
4. or an integer of `0` and a fraction of `200000000`
5. with basic arithmetic, you can get max price automatically from floating-point numbers

https://github.com/DeFiCh/jellyfish/blob/78f2509421c86e29da77c771cd6371044f5e5fbb/packages/jellyfish-transaction/src/script/defi/dftx_pool.ts#L43-L54

Also, to rename https://github.com/DeFiCh/jellyfish/tree/main/packages/jellyfish-transaction/src/script/defi directory to `dftx`.

/triage accepted
/area jellyfish-transaction
/priority urgent-now

**Comment by Jouzo** [comment]
I've been going through this and thinking about different ways to implement it. 
Is there a reason why we should not replace 
` { 
   fromBuffer (buffer: SmartBuffer) { 
     const integer = readBigNumberUInt64(buffer) 
     const fraction = readBigNumberUInt64(buffer) 
     ps.maxPrice = { integer, fraction } 
   }, 
   toBuffer (buffer: SmartBuffer) { 
     const { integer, fraction } = ps.maxPrice 
     writeBigNumberUInt64(integer, buffer) 
     writeBigNumberUInt64(fraction, buffer) 
   } 
 } `
by 
`ComposableBuffer.satoshiAsBigNumber(() => ps.maxPrice, v => ps.maxPrice = v)` 
and changing maxPrice property to BigNumber ?

As far I can tell, all the other composers use satoshiAsBigNumber to handle BigNumber properties.

Let me know if I am missing something

**Comment by fuxingloh** [comment]
> I've been going through this and thinking about different ways to implement it.
> Is there a reason why we should not replace
> `{ fromBuffer (buffer: SmartBuffer) { const integer = readBigNumberUInt64(buffer) const fraction = readBigNumberUInt64(buffer) ps.maxPrice = { integer, fraction } }, toBuffer (buffer: SmartBuffer) { const { integer, fraction } = ps.maxPrice writeBigNumberUInt64(integer, buffer) writeBigNumberUInt64(fraction, buffer) } }`
> by
> `ComposableBuffer.satoshiAsBigNumber(() => ps.maxPrice, v => ps.maxPrice = v)`
> and changing maxPrice property to BigNumber ?
> 
> As far I can tell, all the other composers use satoshiAsBigNumber to handle BigNumber properties.
> 
> Let me know if I am missing something

Take a look at this that was implemented by the early devs https://github.com/DeFiCh/ain/blob/ff869527f245632d19bba7c2a06ae8fa341cdd67/src/masternodes/poolpairs.cpp#L387

satoshi is a `16 byte, 128bit` number normalized of decimal places

However `PoolPairSwapp.maxPrice` is presented as 32 byte with first 16 byte being `integer`, last 16 byte being `fractional` aka satoshi.

If we were to lose `satoshiAsBigNumber` we would only be encoding 16 bytes instead of the required 32 bytes.

**Comment by Jouzo** [comment]
Ok got it. 
The current interface is documented as :
`maxPrice: {
    integer: BigNumber // --------------| 8 bytes
    fraction: BigNumber // -------------| 8 bytes
  }`
 But it should have been 16 bytes each then ?

**Comment by fuxingloh** [comment]
> Ok got it.
> The current interface is documented as :
> `maxPrice: { integer: BigNumber // --------------| 8 bytes fraction: BigNumber // -------------| 8 bytes }`
> But it should have been 16 bytes each then ?

Oh my bad, it's 8+8 bytes. I got confused with it being 16 characters when presented in hex-decimal format.

**Comment by Jouzo** [comment]
Ok, thanks for the clarification
