### ISSUE TITLE
`DeFiCh/ain:1.9.x` On-Chain Governance RPCs implementation

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/jellyfish#458]
Similar to https://github.com/DeFiCh/jellyfish/issues/48, this tracks all the RPC methods and categories being implemented in `jellyfish-api-core`. Please tag and update this if you are working on a feature.

As a final docker build is not produced please use the latest `1.9.x` docker builds for your `testcontainers`, https://github.com/DeFiCh/jellyfish/pull/184 for more information on how to set custom image doing development.

### `rpc_proposals.cpp`
> https://github.com/DeFiCh/ain/pull/576/files 

- [x] createcfp @Jouzo #466 
- [x] createvoc @Jouzo #484 
- [x] vote @Jouzo #487 
- [x] listvotes @Jouzo #602
- [x] getproposal @Jouzo #483 
- [x] listproposals @Jouzo #486

**Comment by Jouzo** [comment]
Waiting for multi masternode setup to test listVotes RPC

**Comment by Jouzo** [comment]
Waiting for https://github.com/DeFiCh/ain/pull/646#issue-699839875 to be merged to work on listVotes
