### ISSUE TITLE
PoolSwap `toOpCodes` failed to read

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/jellyfish#494]
#### What happened:
```sh
Too many decimals read from buffer. Will lose precision with more than 8 decimals

      554 |         const fraction = readBigNumberUInt64(buffer)
      555 |         if (fraction.gt(new BigNumber('99999999'))) {
    > 556 |           throw new Error('Too many decimals read from buffer. Will lose precision with more than 8 decimals')
          |                 ^
      557 |         }
      558 |         setter(integer.plus(fraction.dividedBy(ONE_HUNDRED_MILLION)))
      559 |       },
```

#### What you expected to happen:
Previously code is working, guessing the issue was caused by recent update #469

#### How to reproduce it (as minimally and precisely as possible):
https://mainnet.defichain.io/#/DFI/mainnet/tx/700473ec7ca4f6bec261e75342f91825f3c2cf60df1bf1f335b53a2bcd95b994
6a4c4f446654787317a9140806eb42b6d5bb69726909fb6da34a9152afdf048701c7b3240d0000000017a9140806eb42b6d5bb69726909fb6da34a9152afdf048700ffffffffffffff7fffffffffffffff7f

**Comment by fuxingloh** [comment]
> https://github.com/DeFiCh/jellyfish/pull/457#discussion_r669266324

Damn it, I never thought about this. Looks like we need to handle it. 
Is `ffffffffffffff7fffffffffffffff7f` the only anomaly allowed? e.g. is `ffffffffffffff7fffffffffffffff7e` allowed?

If it's just `ffffffffffffff7fffffffffffffff7f` we can just handle that special constant

/triage accepted
/priority urgent-now
/assign @canonbrother

**Comment by canonbrother** [comment]
> > [#457 (comment)](https://github.com/DeFiCh/jellyfish/pull/457#discussion_r669266324)
> 
> Damn it, I never thought about this. Looks like we need to handle it.
> Is `ffffffffffffff7fffffffffffffff7f` the only anomaly allowed? e.g. is `ffffffffffffff7fffffffffffffff7e` allowed?
> 
> If it's just `ffffffffffffff7fffffffffffffff7f` we can just handle that special constant
> 
> /triage accepted
> /priority urgent-now
> /assign @canonbrother

that is caused by null maxPrice, just need to add a special handling for its default `max int64` value will do
https://github.com/DeFiCh/ain/blob/aed00d09075094a3a0cedebde5248c006216ba09/src/masternodes/rpc_poolpair.cpp#L115-L123
