### ISSUE TITLE
Oracle rpcs should allow weightage value from 0 to 255

### ISSUE THREAD

**Issue by jingyi2811** [DeFiCh/jellyfish#509]
#### What would you like to be added:

Improve existing test units for AppointOracle and UpdateOracle rpcs to allow weightage value from 0 to 255.

#### Why is this needed:
Weightage is no longer limited from 1 to 100 after the eunospaya's hard fork.

**Comment by fuxingloh** [comment]
Do you mean `0` - `255`?

/triage accepted
/area jellyfish-api-core
/priority urgent-now for 1.8.x, target https://github.com/DeFiCh/jellyfish/pull/478
/assign @jingyi2811

**Comment by jingyi2811** [comment]
I think I heard 250. I were wrong.

**Comment by jingyi2811** [comment]
I refactor the following text 

1. APPLE to AAPL
2. TESLA to TSLA
3. oracleid to oracleId

and park them in this PR too.
