### ISSUE TITLE
Refactor variables and text in oracle rpcs and dftxs

### ISSUE THREAD

**Issue by jingyi2811** [DeFiCh/jellyfish#514]
#### What would you like to be added:
Should rename the following texts
1) APPLE to AAPL
2) TESLA to TSLA

Should rename the following variable
1) oracleid to oracleId

#### Why is this needed:
APPLE and TESLA are not acronyms
We use oracleId in whale project, not oracleid

**Comment by fuxingloh** [comment]
/triage accepted
/area jellyfish-api-core

wait for `1.8.x` to be merged to prevent conflicts

**Comment by jingyi2811** [comment]
Sure.
