### ISSUE TITLE
Avoid using `.toBe` in jest and refactor existing usage to use `toStrictEqual`

### ISSUE THREAD

**Issue by surangap** [DeFiCh/jellyfish#613]
#### Why is this needed:
https://dev.to/thejaredwilcurt/why-you-should-never-use-tobe-in-jest-48ca
https://stackoverflow.com/questions/30543190/object-is-vs

**Comment by fuxingloh** [comment]
/triage accepted
/area core

I think we can add it into eslint to make to fail lint checks.

**Comment by Jouzo** [comment]
https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-strict-equal.md but warns only on toEqual
