### ISSUE TITLE
Split lambdas into multiple providers and a single publisher

### ISSUE THREAD

**Issue by monstrobishi** [DeFiCh/jellyfish#653]
#### What would you like to be added:

This mainly affects `salmon-lambda-functions`. Instead of publishing prices directly to the blockchain, the flow will look like:
- Provider functions pull price from price provider
- Each provider function stores price, token, currency, and timestamp (and other possible metadata) in DynamoDB
- Publisher function pushes the prices out

#### Why is this needed:

This allows for more flexibility when analysing prices, in particular it allows us to compare outputs from different oracles against each other.

One downside may be introducing more moving parts, more points of failure.

**Comment by monstrobishi** [comment]
One challenge will be the testing. the e2e test may need some mock db provider, unless we replicate using something like https://hub.docker.com/r/amazon/dynamodb-local 

This will require setting up the aws sdk with local parameters

**Comment by monstrobishi** [comment]
After some further thoughts on the impact this will have on the IAC, CI and E2E tests, I want to weigh up the pros and cons of price protection via comparing prices from different oracles. 

I've come to the following conclusions:

- Each individual oracle has already supplied a trusted historical price, so comparing against the historical price should be sufficient
- Comparing prices between multiple oracles may not be 100% useful as the prices come in at different times, leading to a more complex analysis
- Some assets only have 1 or 2 oracles (Granted this drives the need for more providers, but this is a chicken and egg scenario)
- Some providers start 30 min early or late, so certain times of the day we only have 1 provider even for tickers with 3 or 4 providers

**Comment by monstrobishi** [comment]
Adding another note here. The consensus side implementation will need to rely on existing indexed data to determine the other oracle price. This means if we want to implement something that mirrors an eventual consensus side implementation, we should utilise existing indexed not live price provider data. 

This means we can most likely keep the existing architecture and instead utilise whale's oracle price index to fetch the last indexed price of the other oracles to compare against, or perhaps store in a dynamodb but still submit individually.

**Comment by fuxingloh** [comment]
> Adding another note here. The consensus side implementation will need to rely on existing indexed data to determine the other oracle price. This means if we want to implement something that mirrors an eventual consensus side implementation, we should utilise existing indexed not live price provider data.
> 
> This means we can most likely keep the existing architecture and instead utilise whale's oracle price index to fetch the last indexed price of the other oracles to compare against, or perhaps store in a dynamodb but still submit individually.

I was thinking about this over the weekend, I arrived at the same conclusion as you. Introducing a provider that conditionally submits is hard to implement on the consensus side. I won't even bother with DynamoDB as it would introduce unnecessary centralized complexity.

**Comment by fuxingloh** [comment]
moved to another repo
