### ISSUE TITLE
expand Ocean REST API documentation with Oracles API details

### ISSUE THREAD

**Issue by ojimforever** [DeFiCh/jellyfish#873]
#### What happened:

Docs at https://jellyfish.defichain.com/ocean/ section look promising, but lack description of Oracles API despite endpoints being available, i.e.

```
curl https://ocean.defichain.com/v0/mainnet/oracles
{"data":[{"id":"f7a00f517a0201e2517a422c5d2b2807868b2615f17d8fc9d8d2bd6baab905b7"...snip
```

Would be nice to close the gap and bring the up to parity with the RPC API level:
https://jellyfish.defichain.com/node/jellyfish/api/oracle

**Comment by John-Gee** [comment]
Thank you for opening this!
