### ISSUE TITLE
Issue trying to create defi custom transaction

### ISSUE THREAD

**Issue by mauricejerome** [DeFiCh/jellyfish#883]
-resolved-

**Comment by fuxingloh** [comment]
> Error: PoolSwapTx: tx must have at least one input from account owner (code 16)

This error indicated that you are trying to create a transaction without the private keys to the account. Do you have access to the wallet?

**Comment by mauricejerome** [comment]
Yes, I do. It's my testnet wallet and it is connected and unlocked. However, it does not seem to be the only issue. Did you see my command? Is it otherwise 100% correct or is there an issue with the syntax I used?

**Comment by cwkang1998** [comment]
Closing as considered resolve. @fuxingloh
