### ISSUE TITLE
`tGroup.waitForSync()` is not working after `container.restart()`

### ISSUE THREAD

**Issue by surangap** [DeFiCh/jellyfish#915]
#### What happened:
`await tGroup.waitForSync()` won't sync blocks across nodes, instead times out. This is after a container restart. i.e 
```
const masterNode1Addr = await masterNodeProvider1.container.getNewAddress('', 'legacy')
const masterNode1Id = await masterNodeProvider1.container.call('createmasternode', [masterNode1Addr])
await masterNodeProvider1.container.generate(1)

await masterNodeProvider1.container.setDeFiConf([`masternode_operator=${masterNode1Addr}`])
await masterNodeProvider1.container.restart()
```

#### What you expected to happen:
`await tGroup.waitForSync()` to sync blocks 

#### How to reproduce it (as minimally and precisely as possible):
within a test do,
```
const masterNode1Addr = await masterNodeProvider1.container.getNewAddress('', 'legacy')
const masterNode1Id = await masterNodeProvider1.container.call('createmasternode', [masterNode1Addr])
await masterNodeProvider1.container.generate(1)

await masterNodeProvider1.container.setDeFiConf([`masternode_operator=${masterNode1Addr}`])
await masterNodeProvider1.container.restart()
```
then try `await tGroup.waitForSync()`

it might be possible to reproduce the bug after a simple `await masterNodeProvider1.container.restart()` and then `await tGroup.waitForSync()` - not tested.

#### Anything else we need to know?:
Not sure what the exact cause is. need more debugging. Could be that the internal network between nodes is broken after the restart. none of the blocks propagate to other nodes

**Comment by canonbrother** [comment]
hmm.. yea.. need to add the peer again after restart
