### ISSUE TITLE
dumb revive json-rpc value type

### ISSUE THREAD

**Issue by canonbrother** [DeFiCh/jellyfish#93]
#### What would you like to be added:

"smart revive" blockchain amount as bignumber, the rest numeric remains as number.

#### Why is this needed:

strict type and better view for user

**Comment by fuxingloh** [comment]
Yeah, we need this now. But it's more like dumb revive than smart revive.

/triage accepted
/area core
/assign @fuxingloh
/priority important-soon

**Comment by fuxingloh** [comment]
Currently the signature of JellyfishJSON is allow **precision** based parsing, we can add in an additional option to allow view/model based parsing.

### From:
```ts
parse (text: string, precision: Precision): any
```

### To:
```ts
interface PrecisionMapping {
  [key: string]: Precision | PrecisionMapping
}

parse (text: string, precision: PrecisionMapping): any
```
The precision mapping allows manual key based customization of what precision it should be. If precision is not provided it will default to `number`.

### Source is at :

https://github.com/DeFiCh/jellyfish/blob/501ada364d09d8128ceea0228b4f6e4843990c5b/packages/jellyfish-json/src/index.ts#L39-L53
